# Generated by Django 5.1.7 on 2025-05-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(max_length=255, verbose_name='Name of User')),
                ('user_email', models.EmailField(max_length=255, unique=True, verbose_name='Email of User')),
                ('user_cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF User')),
                ('password', models.CharField(max_length=255, verbose_name='Password of User')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('is_trusty', models.BooleanField(default=True, verbose_name='Trusty?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'constraints': [models.UniqueConstraint(fields=('user_email',), name='unique_user_email'), models.UniqueConstraint(fields=('user_cpf',), name='unique_user_cpf')],
            },
        ),
    ]
