# Generated by Django 5.1.7 on 2025-05-26 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily_water_consumption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertWaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_label', models.CharField(max_length=255)),
                ('alert_type', models.CharField(choices=[('EXTREME', 'Consumo excessivo'), ('VERY_HIGH', 'Consumo muito elevado'), ('HIGH', 'Consumo elevado')], max_length=50)),
                ('date_label_of_alert', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Alerta')),
                ('total_consumption_exceeded', models.DecimalField(decimal_places=2, help_text='Quantidade de consumo excedido em L/min', max_digits=20, verbose_name='Consumo Excedido (L)')),
                ('average_consumption', models.DecimalField(decimal_places=2, help_text='Média histórica de consumo em L/min', max_digits=20, verbose_name='Média de Consumo (L)')),
                ('percentage_exceeded', models.DecimalField(decimal_places=2, help_text='Porcentagem de consumo excedido em relação à média', max_digits=5, verbose_name='Porcentagem Excedida (%)')),
                ('dialy_water_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='daily_water_consumption.dailywaterconsumption')),
            ],
            options={
                'db_table': 'alert_water_consumption',
                'ordering': ['-date_label_of_alert'],
            },
        ),
    ]
