# Generated by Django 5.1.7 on 2025-05-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_water_consumption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertwaterconsumption',
            old_name='dialy_water_consumption',
            new_name='daily_water_consumption',
        ),
        migrations.AlterField(
            model_name='alertwaterconsumption',
            name='alert_type',
            field=models.CharField(choices=[('HIGH', 'Consumo elevado'), ('EXTREME', 'Consumo excessivo'), ('VERY_HIGH', 'Consumo muito elevado')], max_length=50),
        ),
    ]
