# Generated by Django 5.1.7 on 2025-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_water_consumption', '0002_rename_dialy_water_consumption_alertwaterconsumption_daily_water_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertwaterconsumption',
            name='alert_type',
            field=models.CharField(choices=[('VERY_HIGH', 'Consumo muito elevado'), ('HIGH', 'Consumo elevado'), ('EXTREME', 'Consumo excessivo')], max_length=50),
        ),
    ]
