# Generated by Django 5.1.7 on 2025-05-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_water_consumption', '0004_alter_alertwaterconsumption_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertwaterconsumption',
            name='alert_type',
            field=models.CharField(choices=[('EXTREME', 'Consumo excessivo'), ('HIGH', 'Consumo elevado'), ('VERY_HIGH', 'Consumo muito elevado')], max_length=50),
        ),
    ]
