# Generated by Django 5.1.7 on 2025-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_water_consumption', '0007_alter_alertwaterconsumption_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertwaterconsumption',
            name='alert_type',
            field=models.CharField(choices=[('EXTREME', 'Consumo excessivo'), ('VERY_HIGH', 'Consumo muito elevado'), ('HIGH', 'Consumo elevado')], max_length=50, verbose_name='Type of Alert'),
        ),
    ]
