# Generated by Django 5.1.7 on 2025-07-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_water_consumption', '0008_alter_alertwaterconsumption_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertwaterconsumption',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Visualizado'),
        ),
        migrations.AlterField(
            model_name='alertwaterconsumption',
            name='alert_type',
            field=models.CharField(choices=[('HIGH', 'Consumo elevado'), ('VERY_HIGH', 'Consumo muito elevado'), ('EXTREME', 'Consumo excessivo')], max_length=50, verbose_name='Type of Alert'),
        ),
    ]
