# Generated by Django 5.1.7 on 2025-06-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_water_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlywaterconsumption',
            name='end_date',
            field=models.DateField(verbose_name='Data de Fim do Mês'),
        ),
        migrations.AlterField(
            model_name='monthlywaterconsumption',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, help_text='Consumo total de água no mês em Litros', max_digits=20, verbose_name='Consumo Total (L)'),
        ),
    ]
