# Generated by Django 5.1.7 on 2025-04-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'weekly_water_consumption',
            },
        ),
    ]
