# Generated by Django 5.1.7 on 2025-06-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_water_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='date_label',
            field=models.CharField(help_text="EX: 'Semana de 01 a 07 de Janeiro de 2025'", max_length=255, verbose_name='Rótulo da Semana'),
        ),
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='end_date',
            field=models.DateField(verbose_name='Data de Fim da Semana'),
        ),
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='start_date',
            field=models.DateField(verbose_name='Data de Início da Semana'),
        ),
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, help_text='Consumo total de água na semana em Litros', max_digits=20, verbose_name='Consumo Total (L)'),
        ),
    ]
