# Generated by Django 5.1.7 on 2025-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_water_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklywaterconsumption',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='date_label',
            field=models.CharField(help_text="EX: 'Semana 01 - 07 de Janeiro de 2025'", max_length=255, verbose_name='Rótulo da Semana'),
        ),
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='end_date',
            field=models.DateField(verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='start_date',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='weeklywaterconsumption',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, help_text='Consumo total em L/min', max_digits=20, verbose_name='Consumo Total (L)'),
        ),
    ]
