# Generated by Django 5.1.7 on 2025-04-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BimonthlyWaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(help_text="EX: 'Janeiro de 2025'", max_length=255, verbose_name='Rótulo do Bimestre')),
                ('start_date', models.DateField(verbose_name='Data de Início do Bimestre')),
                ('end_date', models.DateField(verbose_name='Data do Fim do Bimestre')),
                ('total_consumption', models.DecimalField(decimal_places=2, help_text='Consumo total em L/min', max_digits=20, verbose_name='Consumo Total (L)')),
            ],
            options={
                'db_table': 'bimonthly_water_consumption',
                'ordering': ['-start_date'],
            },
        ),
    ]
