# Generated by Django 5.1.7 on 2025-06-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimonthly_water_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimonthlywaterconsumption',
            name='date_label',
            field=models.CharField(help_text="EX: 'Janeiro e Fevereiro de 2025'", max_length=255, verbose_name='Rótulo do Bimestre'),
        ),
        migrations.AlterField(
            model_name='bimonthlywaterconsumption',
            name='end_date',
            field=models.DateField(verbose_name='Data de Fim do Bimestre'),
        ),
        migrations.AlterField(
            model_name='bimonthlywaterconsumption',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, help_text='Consumo total de água no bimestre em Litros', max_digits=20, verbose_name='Consumo Total (L)'),
        ),
    ]
