# Generated by Django 5.1.7 on 2025-04-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=30)),
                ('flow_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'reader_leak',
            },
        ),
    ]
