# Generated by Django 5.1.7 on 2025-04-20 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader_leak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrating',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
