# Generated by Django 5.1.7 on 2025-04-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader_leak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flowrating',
            table='reader_leak',
        ),
    ]
