# Generated by Django 5.1.7 on 2025-04-23 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader_leak', '0003_alter_flowrating_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowrating',
            old_name='timestamp',
            new_name='times_tamp',
        ),
    ]
