from .weekly_water_consumption_task import weekly_water_consumption_task
from .monthly_water_consumption_task import monthly_water_consumption_task
from .bimonthly_water_consumption_task import bimonthly_water_consumption_task
