# Generated by Django 5.1.7 on 2025-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(help_text="EX: 'Dia 1 de Janeiro de 2025'", max_length=255, verbose_name='Rótulo do Dia')),
                ('total_consumption', models.DecimalField(decimal_places=2, help_text='Consumo total em L/min', max_digits=20, verbose_name='Consumo Total (L)')),
            ],
            options={
                'db_table': 'daily_water_consumption',
            },
        ),
    ]
