# Generated by Django 5.1.7 on 2025-06-02 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_water_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywaterconsumption',
            name='date_of_register',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
