# Generated by Django 5.1.7 on 2025-06-11 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_water_consumption', '0002_dailywaterconsumption_date_of_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailywaterconsumption',
            options={'ordering': ['-date_of_register']},
        ),
        migrations.AlterField(
            model_name='dailywaterconsumption',
            name='date_label',
            field=models.CharField(help_text="EX: '01 de Janeiro de 2025'", max_length=255, verbose_name='Rótulo do Dia'),
        ),
        migrations.AlterField(
            model_name='dailywaterconsumption',
            name='date_of_register',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Registro'),
        ),
        migrations.AlterField(
            model_name='dailywaterconsumption',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, help_text='Consumo total de água no dia em Litros', max_digits=20, verbose_name='Consumo Total (L)'),
        ),
    ]
