# Generated by Django 5.1.7 on 2025-05-20 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_tamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('flow_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'flow_rating',
            },
        ),
    ]
