# Generated by Django 5.1.7 on 2025-06-11 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowrating',
            options={'ordering': ['-times_tamp']},
        ),
        migrations.AlterField(
            model_name='flowrating',
            name='flow_rate',
            field=models.DecimalField(decimal_places=2, help_text='Vazão de água medida em L/min (Litros por minuto)', max_digits=6, verbose_name='Taxa de Vazão'),
        ),
        migrations.AlterField(
            model_name='flowrating',
            name='times_tamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horário da Medição'),
        ),
    ]
